### ISSUE TITLE
DTP error, scheduling to the past

### ISSUE THREAD

**Issue by gaixas1** [kvetak/RINA#6] opened 2015-04-29 06:33 UTC
There is an error at DTP::schedule, when QoS ATime is left as undefined (-1).
In that case, as this function takes this value directly, it considers -1 as a valid time and then can try to schedule messages to past times.

I propose to compute MPL, R and A before the scheduling (checking that there is no invalid value) and then on the switch make it clearer. E.g.  scheduleAt(simTime() + 3 * (MPL+R+A) , timer);  //3(MPL+R+A)

**Comment by screw** [comment] 2015-04-30 22:01
Could you point me to the branch, scenario, config, where I could test it?

**Comment by gaixas1** [comment] 2015-04-30 22:06
Un any escenario, removing atime from qos cube should do the trick.
There are no uploaded examples with that problem working, as only i have
uses qos with undefined parameter and have not this error on muy branch.

**Comment by screw** [comment] 2015-04-30 22:06
Well then there you have it. You cannot remove ATimer from QoSCube.

**Comment by gaixas1** [comment] 2015-05-01 05:30
Then make that parameter def value 0 and not -1, at least for qos cubes. -1
for ae.

**Comment by screw** [comment] 2015-05-01 16:36
There are two problems mixed into one.
There is requirements QoSCube and there is QoSCube supported by the DIF.
We chose to use one class for both at the beginning.
And that's why you cannot have default value that satisfy both cases.
We chose using default values for the requirements QoSCube as there is reasonable expectation that AE specify only some parameters and others are represented as don't care (-1).
On the other hand QoSCube supported by the DIF is expected to be fully specified as there is no default value for (all or at least many of) parameters.
I'll suggest to V splitting QoSCube class into two.

**Comment by gaixas1** [comment] 2015-05-01 16:58
I support the spliting, but having some qos cube parameters as undefined
may be also good, if are really parametets that we don't care or simply
don't know/cannot ensure. E.g. qll qos differ only in delay or we have only
a best effort qos.
Also, mapping qos n to n-1 should be consideres at some point.

**Comment by screw** [comment] 2015-05-01 17:04
If you are referring to what i have described as "QoSCube supported by the DIF", then no, having some parameters as undefined is unacceptable (until somebody proves me otherwise).
The DIF knows what it can and cannot support.
If you are talking about requirements QoSCube, then undefined value is do-not-care value, and that is already in.

**Comment by gaixas1** [comment] 2015-05-01 17:41
Well the problemas here is that we have 3 things expresed in the same way.
App requirements, what an app needs to work well.
Qos cube, internal qos clases of each DIF used to distingish flows.
Flow "qos", what an n-1 flow really provides.

A DIF must know what n-1 flows provide un order to use them, but to
distingish its own flows, only need the qos páramos that really afect how
those flows are treated. So if we have for example a DIF that only gives us
best effort flows with or without retransmission, only the parapeters that
decide that are needed un the qos cubes (as that is something only used
within the dif and unknown to upper/lower layers.

Pd. Requests on n-1 flows on n flow allocation should be treated un the
same way as request from apps. But simplifiying, a qos cube should have its
supported params + required n-1 qos (e.g. we ensure delay <1ms, but require
delay <0.1 ms on n-1 flows in order to ensure our delay).

**Comment by screw** [comment] 2015-05-01 17:59
Closing this bug as it is not a bug. Moving the discussion to skype.

**Closed by screw** 2015-05-01 17:59 UTC
